# Generated by Django 4.1.1 on 2022-09-30 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flyingsite',
            options={'ordering': ['-updated_on']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='flying_site',
            new_name='pilot',
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, unique=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('taken_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_on'],
            },
        ),
    ]
