# Generated by Django 4.1.1 on 2022-09-30 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='pilot@pilot.com', max_length=254),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='Unknown Pilot', max_length=100),
        ),
    ]
