# Generated by Django 4.1.1 on 2022-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_alter_flyingsite_wind_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flyingsite',
            name='wind_direction',
            field=models.CharField(choices=[('N', 'N'), ('NW', 'NW'), ('NE', 'NE'), ('S', 'S'), ('SE', 'SE'), ('SW', 'SW'), ('E', 'E'), ('W', 'W')], max_length=150),
        ),
    ]
