# Generated by Django 4.1.1 on 2022-10-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_flyingsite_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='flyingsite',
            name='discussion',
            field=models.TextField(default='Yet to be discussed'),
            preserve_default=False,
        ),
    ]
