# Generated by Django 4.1.1 on 2022-10-05 08:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_flyingsite_discussion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='taken_by',
            new_name='uploaded_by',
        ),
        migrations.AddField(
            model_name='photos',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
