# Generated by Django 4.1.1 on 2022-10-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_photo_delete_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
