# Generated by Django 4.1.1 on 2022-10-05 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_photo_approved_photo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='slug',
            field=models.SlugField(default='slug', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
